export const listPejabat: Array<any> = [
  {
    legislatif: [
      {
        id_komisi: 1,
        komisi: "Komisi IV",
        description:
          "(Pertanian, Lingkungan Hidup dan Kehutanan, dan, Kelautan)",
        anggota: [
          {
            id_anggota: 1,
            name: "Mukhamad Misbakhun",
            jabatan: "Golkar, Dapil Jatim II",
            image: "legislatif_1_1.png",
            description: [
              "LHKPN (NHK 266627)\nRp 35.996.196.799 (2018)\nRP. - 		                   (2019)\nRp 35.381.586.129 (2020)\nRp 34.885.793.129 (2021)\nRp 36.694.895.129 (2022)\n",
              "Pernah melakukan bakti sosial bersama HM Sampoerna pada tahun 2018",
              "Pernah divonis bersalah atas kasus pemalsuan pencairan Deposito dalam penerbitan Fasilitas L/C Bank Century seilai sekitar 200M",
              "Total Sumbangan Dana Kampanye ke Partai: Rp 192.185.875",
              "Menolak kenaikan cukai dan revisi PP 109",
              "TI champion: Pengusul RUU Pertembakauan yang tidak berpihak pada kesehatan masyarakat",
              "Kontra TC",
              "Meminta pemerintah merevisi besaran tarif CHT khusus SKT sbesar 2% saja",
              "Hadir saat pertemuan dengan Direksi PT. Gudang Garam Tbk. di Surabaya, Jawa Timur, Kamis (08/2/2018)",
            ],
          },
          {
            id_anggota: 2,
            name: "Ir. PANGGAH SUSANTO, M.M.",
            jabatan: "Golkar, Jateng VI",
            image: "legislatif_1_2.png",
            description: [
              "LHKPN (NHK 73739) :\nRp 21.677.808.574 (2019)\nRp 21.834.353.325 (2020)\nRp 22.542.484.768 (2021)\nRp 21.020.720.498 (2022)\n",
              "Total Sumbangan Dana Kampanye ke Partai: Rp 460.740.000",
              "Kontra TC",
              "Ikut dalam kunjungan kerja dalam rangka meninjau langsung penyerapan tembakau di gudang milik PT Gudang Garam dan PT Djarum di Temanggung",
            ],
          },
          {
            id_anggota: 3,
            name: "Sudin, SE",
            jabatan: "PDIP, Dapil Lampung I",
            image: "legislatif_1_3.png",
            description: [
              "Anak: Crescentia Sherly Sudin. Kerja sebagai Senior Business Analyst PT Japfa Comfeed Indonesia, Tbk (menantu juga)",
              "LHKPN (NHK 266633):\nRp 20.077.671.285 (2018)\nRp -  (2019)\nRp 35.269.012.452 (2020)\nRp 34.822.712.377 (2021)\nRp 39.716.682.154 (2022)\n",
              "Total Sumbangan Dana Kampanye ke Partai 2018: Rp 1.562.900.000",
              "Kontra TC",
              // HAS CHILD: Mempersoalkan harga tembakau yang anjlok (khususnya di Probolinggo), meminta ada regulasi yang mengatur hal tsb
            ],
          },
          {
            id_anggota: 4,
            name: "Firman Soebagyo",
            jabatan: "Golkar. Dapil Jawa Tengah III",
            image: "legislatif_1_4.png",
            description: [
              "Total Sumbangan Dana Kampanye ke Partai: Rp 1.126.905.000",
              "Kontra TC",
              "LHKPN (NHK 179668):\nRp 13.064.944.834 (2018)\nRp 13.013.944.834 (2020)\nRp 13.176.216.107 (2021)\nRp 14.375.711.000 (2022)\n",
              "KADIN indonesia, Sebagai: Komite tetap penghubung antar Lembaga KADIN Indonesia dan DPR RI. Tahun: 2015 - 2020",
              "Firman Subagyo mendukung sikap APTI terkait rokok dan tembakau serta menolak RUU Kesehatan terkait regulasi tembakau",
            ],
          },
          {
            id_anggota: 5,
            name: "Drs. H. IBNU MULTAZAM",
            jabatan: "PKB, Jawa Timur VII\nBaleg",
            image: "legislatif_1_5.png",
            description: [
              "Anggota pansus RUU Pertembakauan",
              "LHKPN (38516):\nRp 5.480.177.968 (2018)\nRp 20.630.194.285 (2021)\nRp 23.785.204.285 (2022)\n",
              "Sumbangan Dana Kampanye ke Partai 2018: Rp. 230.000.000",
              "Dalam pertemuan APTI dengan PKB yg membahas terkait permintaan APTI utk DPR menolak adanya kenaikan cukai rokok , Ibnu Multazam yg menjadi perwakilan FPKB dan Komisi IV menanggapi dg positif (menjelaskan bhw PKB mendukung apa yg APTI perjuangkan, keluhan tsb akan disampaikan kepada komisi IV dan merencanakan adanya pertemuan antara DPR, Pemerintah, petani dan industri rokok)",
              "Kontra TC",
            ],
          },
          {
            id_anggota: 6,
            name: "Vita Ervina, S.E.",
            jabatan: "PDIP, Jateng VI",
            image: "legislatif_1_6.png",
            description: [
              "Tembakau  memberikan kontribusi yang besar bagi perekonomian nasional",
              "Total Sumbangan Dana Kampanye ke Partai: Rp 990.258.980",
              "LHKPN (NHK 542070):\nRp 2.938.000.000 (2019)\nRp 3.559.011.000 (2020)\nRp 3.468.645.348 (2021)\nRp 4.993.161.102 (2022)\n",
            ],
          },
          {
            id_anggota: 7,
            name: "Daniel Johan, SE, MM",
            jabatan: "PKB, Kalbar I",
            image: "legislatif_1_7.png",
            description: [
              "Kontra TC",
              "LHKPN (NHK 180468)\nRp 52.021.139.421 (2018)\nRp 61.448.001.089 (2019)\nRp 67.820.668.898 (2020)\nRp 73.863.807.788 (2021)\nRp 74.157.761.284 (2022)\n",
              "Total Sumbangan Dana Kampanye ke Partai: Rp 1.800.000.000",
            ],
          },
          {
            id_anggota: 8,
            name: "Ir. KRT H. DARORI WONODIPURO, M.M., IPU.",
            jabatan: "Gerindra, Jateng VII",
            image: "legislatif_1_8.png",
            description: [
              "Kontra TC",
              "Termasuk Tim Pansus RUU Pertembakauan yang kunjungan ke TI",
              "Perusahaan:\nPT Sumatera Silva Lestari, Komisaris (tdk ada info tahun)\nPT Inhutani III, Komisaris utama (tdk ada info tahun)\nPertamina Geothermal, Komisaris (tdk ada info tahun)",
              "Sumbangan Dana Kampanye ke Partai 2018: Rp. 1.258.500.000",
              "LHKPN (NHK 11266)\nRp. 12.431.262.347 (2018)\nRp. 11.627.490.061 (2019)\nRp. 11.317.742.303 (2020)\nRp. 11.903.007.315	(2021)\nRp.11.592.000.739	(2022)\n",
            ],
          },
          {
            id_anggota: 9,
            name: "Sunarna",
            jabatan: "PDIP, Jateng VIII",
            image: "legislatif_1_9.png",
            description: [
              "Tahun 2013, saat menjabat bupati klaten, menemui petani dan menyatakan mendukung penolakan PP tersebut dengan menandatangani surat dukungan penolakan PP yang akan dikirim ke pemerintah pusat",
            ],
          },
          {
            id_anggota: 10,
            name: "BAMBANG PURWANTO, S.ST., M.H.",
            jabatan: "Demokrat, Kalteng",
            image: "legislatif_1_10.png",
            description: [
              "Kontra TC",
              "LHKPN (69539) :\nRp 951.624.000 (2019)\nRp 930.176.512 (2021)\nRp 1.290.217.902 (2022)\n",
              "Bupati KABUPATEN KOTA WARIGIN BARAT Tahun 2015",
              "Sumbangan dana kampanye ke partai tahun 2019 sebesar Rp 1.753.700.000",
            ],
          },
        ],
      },
      {
        id_komisi: 2,
        komisi: "Komisi VI",
        description: "(Industri, Investasi, Persaingan Usaha)",
        anggota: [
          {
            id_anggota: 1,
            name: "Nusron Wahid",
            jabatan: "Golkar, Dapil Jateng II",
            image: "legislatif_2_1.png",
            description: [],
          },
          {
            id_anggota: 2,
            name: "Adisatrya Suryo Sulisto",
            jabatan: "PDIP, Dapil Jateng VIII",
            image: "legislatif_2_2.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "M. SARMUJI, SE., M.Si.",
            jabatan: "Fraksi Golkar. Dapil Jawa Timur VI",
            image: "legislatif_2_3.png",
            description: [],
          },
          {
            id_anggota: 4,
            name: "Dr. SUPRATMAN ANDI AGTAS, S.H., M.H.",
            jabatan:
              "Gerindra. Dapil Sulawesi Tengah\nKetua BALEG 2016-Sekarang",
            image: "legislatif_2_4.png",
            description: [],
          },
          {
            id_anggota: 5,
            name: "LULUK NUR HAMIDAH, M.Si., M.PA.",
            jabatan:
              "PKB. Dapil Jawa Tengah IV\nAnggota Baleg, Pansus dan Komisi VI",
            image: "legislatif_2_5.png",
            description: [],
          },
          {
            id_anggota: 6,
            name: "Johanes ARIA BIMA Trihastoto",
            jabatan: "Fraksi PDIP. Dapil Jawa Tengah V",
            image: "legislatif_2_6.png",
            description: [],
          },
          {
            id_anggota: 7,
            name: "I NYOMAN PARTA, S.H.",
            jabatan: "PDIP. Dapil Bali",
            image: "legislatif_2_7.png",
            description: [],
          },
          {
            id_anggota: 8,
            name: "Rieke Diah Pitaloka M.Hum",
            jabatan:
              "PDIP. Dapil Jawa Barat VII\nKetua Umum Konfederasi Rakyat Pekerja Indonesia (KPRI)",
            image: "legislatif_2_8.png",
            description: [],
          },
          {
            id_anggota: 9,
            name: "Faisol Riza",
            jabatan: "PKB. Dapil Jawa Timur II\nKetua Komisi VI",
            image: "legislatif_2_9.png",
            description: [],
          },
        ],
      },
      {
        id_komisi: 3,
        komisi: "Komisi VII",
        description: "(Energi, Riset dan Teknologi, dan Lingkungan Hidup)",
        anggota: [
          {
            id_anggota: 1,
            name: "Marwan Jafar",
            jabatan: "PKB, Jawa Tengah III",
            image: "legislatif_3_1.png",
            description: [],
          },
          {
            id_anggota: 2,
            name: "Sartono Hutomo",
            jabatan: "Demokrat, Dapil Jatim VII",
            image: "legislatif_3_1.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "Bambang Haryadi",
            jabatan: "Gerindra, Dapil Jatim IV",
            image: "legislatif_3_3.png",
            description: [],
          },
          {
            id_anggota: 4,
            name: "Abdul Kadir Karding",
            jabatan: "PKB, Dapil Jateng V",
            image: "legislatif_3_4.png",
            description: [],
          },
          {
            id_anggota: 5,
            name: "Ir H.M.Ridwan Hisjam",
            jabatan: "Golkar, Dapil Jatim V",
            image: "legislatif_3_5.png",
            description: [],
          },
          {
            id_anggota: 6,
            name: "Ribka Tjiptaning Proletariyati",
            jabatan: "PDIP, Dapil Jabar IV",
            image: "legislatif_3_6.png",
            description: [],
          },
          {
            id_anggota: 7,
            name: "Syaikhul Islam Ali",
            jabatan: "PKB, Dapil Jatim I",
            image: "legislatif_3_7.png",
            description: [],
          },
        ],
      },
      {
        id_komisi: 4,
        komisi: "Komisi IX",
        description: "(Kesehatan, Ketenagakerjaan, Kependudukan)",
        anggota: [
          {
            id_anggota: 1,
            name: "Hj. NUR NADLIFAH, S.Ag., M.M.",
            jabatan: "PKB, Jawa Tengah IX",
            image: "legislatif_4_1.png",
            description: [
              "Meminta Pasal zat adiktif dikeluarkan dari RPP Kesehatan dan diatur secara terpisah",
              "Sumbangan Dana Kampanye ke Partai 2018: Rp. 29.497.000",
              "Banyak pihak yang mendorong pemerintah untuk mengambil kebijakan yang mengancam keberlangsungan industri hasil tembakau melalui kampanye-kampanye hitam antitembakau. Padahal, menurut Nur, seringkali kampanye-kampanye yang dilakukan tak berdasar dan tanpa data.",
              "LHKPN (NHK 539836)\nRp. -	 (2018)\nRp. 1.347.065.724	 (2019)\nRp. -		(2020)\nRp. 2.809.365.724	 (2021)\nRp. 8.108.657.057	(2022)",
              "Kontra TC",
            ],
          },
          {
            id_anggota: 2,
            name: "Dra. Lucy Kurniasari",
            jabatan: "Demokrat, Jawa Timur I",
            image: "legislatif_4_2.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "M. Yahya Zaini, S.H",
            jabatan: "Golkar, Jawa Tengah VIII",
            image: "legislatif_4_3.png",
            description: [],
          },
          {
            id_anggota: 4,
            name: "H. Abidin Fikri, S.H. M.H",
            jabatan: "PDIP, Jawa Tengah IX",
            image: "legislatif_4_4.png",
            description: [],
          },
        ],
      },
      {
        id_komisi: 5,
        komisi: "Komisi XI",
        description:
          "(Keuangan, Perencanaan Pembangunan Nasional, serta Perbankan)",
        anggota: [
          {
            id_anggota: 1,
            name: "Ir. Andreas Eddy",
            jabatan: "PDIP, Dapil Jatim V",
            image: "legislatif_5_1.png",
            description: [],
          },
          {
            id_anggota: 2,
            name: "Prof. Dr. Hendrawan Supratikno",
            jabatan: "PDIP, Dapil Jateng X",
            image: "legislatif_5_2.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "Bertu Merlas",
            jabatan: "PKB, Dapil Sumsel II",
            image: "legislatif_5_3.png",
            description: [],
          },
          {
            id_anggota: 4,
            name: "H. M. Amir Uskara",
            jabatan: "PPP, Dapil Sulsel I",
            image: "legislatif_5_4.png",
            description: [],
          },
          {
            id_anggota: 5,
            name: "Willy Aditya",
            jabatan:
              "Wakil Ketua Fraksi Partai NasDem DPR RI.\nDapil Jawa Timur XI\nWakil Ketua Badan Legislasi DPR RI\nKetua DPP Partai Nasdem",
            image: "legislatif_5_5.png",
            description: [],
          },
          {
            id_anggota: 6,
            name: "Racmat Gobel",
            jabatan: "Nasdem, Dapil Gorontalo 1",
            image: "legislatif_5_6.png",
            description: [],
          },
          {
            id_anggota: 7,
            name: "Ir. Dolfie Othniel Frederic Palit",
            jabatan: "PDIP, Dapil Jateng IV",
            image: "legislatif_5_7.png",
            description: [],
          },
          {
            id_anggota: 8,
            name: "Dr. H. Mustofa, SE., MM",
            jabatan: "PDIP, Dapil Jateng II",
            image: "legislatif_5_8.png",
            description: [],
          },
          {
            id_anggota: 9,
            name: "Said Abdullah",
            jabatan: "PDIP, Dapil Jatim XI",
            image: "legislatif_5_9.png",
            description: [],
          },
          {
            id_anggota: 10,
            name: "Ir. Andreas Eddy",
            jabatan: "PDIP, Dapil Jatim V",
            image: "legislatif_5_10.png",
            description: [],
          },
        ],
      },
    ],
  },
  {
    eksekutif: [
      {
        id_kementerian: 1,
        kementerian: "Kementerian Perekonomian",
        anggota: [
          {
            id_anggota: 1,
            name: "Atong Soekirman",
            jabatan: "Asisten Deputi Pengembangan Industri",
            image: "eksekutif_1_1.png",
            description: [],
          },
          {
            id_anggota: 2,
            name: "Airlangga Hartanto",
            jabatan: "Menko Perekonomian, Golkar",
            image: "eksekutif_1_2.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "Moch Edy Yusuf",
            jabatan: "Asisten Deputi Pengembangan Agribisnis Perkebunan",
            image: "eksekutif_1_3.png",
            description: [],
          },
          {
            id_anggota: 4,
            name: "Susiwijono Moegiarso",
            jabatan: "Sekretaris",
            image: "eksekutif_1_4.png",
            description: [],
          },
        ],
      },
      // PUNYA CHILD NODE
      {
        id_kementerian: 2,
        kementerian: "Kementerian Keuangan",
        anggota: [
          {
            id_anggota: 1,
            name: "Sri Mulyani Indrawati",
            jabatan: "Menteri Keuangan Indonesia",
            image: "eksekutif_2_1.png",
            description: [],
            child: [
              {
                relation:
                  "dilantik oleh Menteri Keuangan Sri Mulyani Indrawati pada 2 Maret 2020",
                id_anggota: 1,
                name: "Eddy Abdurachman",
                jabatan: "Direktur Utama BPDPKS",
                image: "eksekutif_child_2_1.png",
                description: [
                  "Dewan Komisaris bertugas mengawasi manajemen Perusahaan dan memberikan arahan kepada Direksi terkait pengembangan bisnis sejalan dengan visi dan misi Perusahaan untuk tahun buku berjalan.",
                  "Menjabat juga sebagai Komisaris Independen di PT Bentoel Internasional Investama Tbk sejak Februari 2015 hingga saat ini.",
                ],
              },
            ],
          },
        ],
      },
      {
        id_kementerian: 3,
        kementerian: "Kementerian Perindustrian",
        anggota: [
          {
            id_anggota: 1,
            name: "Edy Sutopo",
            jabatan:
              "Direktur Industri Minuman, Hasil Tembakau dan Bahan Penyegar",
            image: "eksekutif_3_1.png",
            description: [],
          },
          {
            id_anggota: 2,
            name: "Putu Juli Ardika",
            jabatan: "Direktur Jenderal Industri Agro",
            image: "eksekutif_3_2.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "Agus Gumiwang Kartasasmita",
            jabatan: "Menteri Perindustrian",
            image: "eksekutif_3_3.png",
            description: [],
          },
        ],
      },
      {
        id_kementerian: 4,
        kementerian: "Kementerian Pertanian",
        anggota: [
          {
            id_anggota: 1,
            name: "Yaqub Ginting",
            jabatan: "Ketua Tim Kerja Tanaman Semusim dan yang Lainnya",
            image: "eksekutif_5_1.png",
            description: [],
          },
          {
            id_anggota: 2,
            name: "Kasdi Subagyono",
            jabatan: "Sekertaris Jenderal Perkebunan Kementan",
            image: "eksekutif_5_2.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "Amran Sulaiman",
            jabatan: "Menteri Pertanian",
            image: "eksekutif_5_3.png",
            description: [],
          },
        ],
      },
      {
        id_kementerian: 5,
        kementerian: "Kementerian Perdagangan",
        anggota: [
          {
            id_anggota: 1,
            name: "Zulkifli Hasan",
            jabatan: "Menteri Perdagangan, PAN",
            image: "eksekutif_5_1.png",
            description: [],
          },
          {
            id_anggota: 2,
            name: "Jerry Sambuaga",
            jabatan: "Wakil Menteri Perdagangan RI, Golkar",
            image: "eksekutif_5_2.png",
            description: [],
          },
          {
            id_anggota: 3,
            name: "Veri Anggriono",
            jabatan: "Staff Ahli Bidang Manajemen dan Tata Kelola",
            image: "eksekutif_5_3.png",
            description: [],
          },
        ],
      },
    ],
  },
  {
    tobacco_industri: [
      { id_industri: 1, name: "PT HM Sampoerna Tbk", image: "sampoerna.png" },
      { id_industri: 2, name: "PT Gudang Garam", image: "gudang-garam.png" },
      {
        id_industri: 3,
        name: "PT Bentoel Internasional Investama Tbk",
        image: "bentoel.png",
      },
      { id_industri: 4, name: "PT Djarum", image: "djarum.png" },
    ],
  },
];
