const legislatif = {
  id: "90",
  nama: "Legislatif",
  position: { x: -1600, y: 0 },
  details: [
    {
      id: "1",
      nama: "Komisi IV",
      position: { x: 0, y: 0 },
      description: "(Pertanian, Lingkungan Hidup dan Kehutanan, dan, Kelautan)",
      anggota: [
        {
          id: "2",
          nama: "Mukhamad Misbakhun",
          position: { x: 0, y: 0 },
          jabatan: "Golkar, Dapil Jatim II",
          image: "legislatif_1_1.jpg",
          details: [
            "2010.  hukumonline.com. Tersangka pemalsuan dokumen akta gadai dan surat kuasa pencairan deposito dalam penerbitan letter of credit Bank Century dan divonis satu tahun penjara.",
            "2017, Merupakan anggota panitia khusus RUU pertembakauan : ",
            "2018,  Pada masa reses pernah menggelar bakti sosial berupa pengobatan gratis bagi warga Nguling, Pasuruan, bersama salah satu perusahaan rokok terbesar di Indonesia, PT HM Sampoerna. ",
            "2018, Hadir saat pertemuan dengan Direksi PT. Gudang Garam Tbk. di Surabaya, Jawa Timur.",
            '2020. Menuduh strategi kebijakan fiskal yang bertujuan menurunkan prevalensi perokok yang dikeluarkan pemerintah pemerintah ingin menghancurkan industri hasil tembakau (IHT)."Kalau hanya berpikir kesehatan saja ya buyar. Apalagi kalau bicara perokok pemula. Yang mau disasar perokok pemula, tapi yang mau dihancurkan industrinya"',
            "2020,.Menyatakan bahwa industri hasil tembakau (IHT) merupakan salah satu industri strategis nasional yang mempunyai andil besar dalam perekonomian Indonesia dan pemerintah masih bergantung pada IHT sebagai industri penopang penerimaan negara",
            "2022, Menyatakan kontra pada rencana Revisi PP 109 yang dinilai hanya memperhatikan aspek kesehatan, menilai bahwa industri ini sudah menyumbang triliunan per tahun kepada negara. menyatakan bahwa petani tembakau tidak pernah mendapatkan haknya sebagai Petani Indonesia. ",
            "2022, Meminta pemerintah merevisi besaran tarif CHT khusus SKT. Berpendapat bahwa kenaikan CHT yang paling rasional untuk SKT di tengah kondisi ekonomi yang belum membaik adalah sebesar 2% saja.",
          ],
        },
        {
          id: "3",
          nama: "Ir. PANGGAH SUSANTO, M.M.",
          position: { x: 0, y: 0 },
          jabatan: "Golkar, Jateng VI",
          image: "legislatif_1_2.jpg",
          details: [
            "2015. Saat menjabat Direktur Jenderal Industri Agro Kementerian Perindustrian (Kemenperin) dirinya mendorong agar kenaikan cukai rokok tidak lebih dari Rp 85 per batang karena berpendapat bahwa hal ini dapat berimbas pada perusahaan yang gulung tikar. ",
            "2017.Menghadiri Diskusi Pertanian dan Industri Tembakau di Kantor  Desa Pijot Utara, Lombok Timur, yang diselenggarakan oleh Gaprindo yang merupakan gabungan perusahaan rokok seperti PT HM Sampoerna Tbk. (Sampoerna) dan PT Bentoel International Investama Tbk (Bentoel Group) yang salah satunya adalah membahas terkait sinergi perusahaan rokok dengan pemerintah dengan dalih kepentingan pemberdayaan petan",
            "2021. Ikut dalam kunjungan kerja dalam rangka meninjau langsung penyerapan tembakau di gudang milik PT Gudang Garam dan PT Djarum di Temanggung bersama Plt Kemenperin dan Bupat Temanggung. Pada kesempatan itu, Panggah meminta agar pemerintah, utamanya Kemenperin menjaga pabrik rokok untuk tumbuh dengan sehat. ",
            "2022, meminta penyusunan RPP Kesehatan dibatalkan karena bersikap diskriminatif terhadap Industri Hasil Tembakau dan komoditi Tembakau. ",
          ],
        },
        {
          id: "4",
          nama: "Sudin, SE",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Lampung I",
          image: "legislatif_1_3.jpg",
          details: [
            '2020. Memberi tanggapan dan perhatian pada harga tembakau yang anjlok (khususnya di Probolinggo), dan menyatakan dukungan untuk adanya penyesuaian regulasi terkait penurunan harga tembakau yang "disinyalir" disebabkan oleh kenaikan cukai rokok. "Jika memang regulasi  harus diatur, ya kita usahakan regulasinya, karena kasihan di beberapa wilayah selalu \'complain\' masalah itu," kata Sudin.',
          ],
        },
        {
          id: "5",
          nama: "Firman Soebagyo",
          position: { x: 0, y: 0 },
          jabatan: "Golkar. Dapil Jawa Tengah III",
          image: "legislatif_1_4.jpg",
          details: [
            "2015. Saat menjabat sebagai Wakil Ketua Baleg, Firman mengaku menjadi pengusul pertama pasal kretek di RUU Kebudayaan karena menilai kretek adalah warisan budaya. ",
            "2023. Mendukung sikap Asosiasi Petani Tembakau Indonesia (APTI) yang tegas menolak selipan pasal-pasal tentang pertembakauan dalam Rancangan Undang-Undang (RUU) Kesehatan.",
            "2023. Merasa keberatan dan menentang DIM (Daftar Inventarisasi Masalah) RUU Omnibus law Kesehatan yang tertuang di Pasal 154, yang mengelompokkan tembakau sebagai kategori narkoba.",
            "2023. Menyatakan bahwa tembakau telah memberikan kontribusi besar bagi penerimaan negara dengan pajak cukainya.",
            "2023. Menyatakan dengan tegas tidak melarang industri  rokok Vape, dan hanya perlu pengawasan pemerintah melalui BPOM untuk memastikan bahan bakunya dibuat murni dari tembakau.",
          ],
        },
        {
          id: "6",
          nama: "Drs. H. IBNU MULTAZAM",
          position: { x: 0, y: 0 },
          jabatan: "PKB, Jawa Timur VII\nBaleg",
          image: "legislatif_1_5.jpg",
          details: [
            "2016. Menekan adanya kalimat perlindungan dan pembudidayaan petani tembakau dalam RUU pertembakauan.",
            "2017. Ibnu merupakan anggota panitia khusus RUU pertembakauan.",
            "2020. Dalam pertemuan APTI dengan PKB yang membahas terkait permintaan APTI agar DPR menolak adanya kenaikan cukai rokok, Ibnu Multazam selaku perwakilan FPKB dan Komisi IV menanggapi dengan positif dan menjelaskan bahwa PKB mendukung apa yg APTI perjuangkan dan akan menyampaikan keluhan kepada komisi IV serta merencanakan adanya pertemuan antara DPR, Pemerintah, petani dan industri rokok.",
          ],
        },
        {
          id: "7",
          nama: "Vita Ervina, S.E.",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Jateng VI",
          image: "legislatif_1_6.jpg",
          details: [
            "2023. Menyatakan tidak setuju dan meminta pemerintah membatalkan RUU Kesehatan pasal 154 ayat 3 dengan dalih pasal tersebut merugikan petani tembakau dan berpendapat bahwa membandingkan zat nikotin dalam rokok tidak sebanding dengan yang ada di narkotika. ",
            "2023. Berpendapat bahwa tembakau memberikan kontribusi yang besar bagi perekonomian nasional.",
            "LHKPN tahun 2022 sebesar Rp 4.993.161.102 dan melaporkan total sumbangan dana kampanye ke partai sebesar  Rp 990.258.980 atau sekitar 20% dari LHKPN. Kader partai yang cukup loyal ya?",
          ],
        },
        {
          id: "8",
          nama: "Daniel Johan, SE, MM",
          position: { x: 0, y: 0 },
          jabatan: "PKB, Kalbar I",
          image: "legislatif_1_7.jpg",
          details: [
            "2016. Memperjuangkan agar UU Tembakau bisa digolkan dengan dalih membantu menyelamatkan petani tembakau di Indonesia.",
            '2021. Terkait rencana revisi Peraturan Pemerintah (PP) Nomor 109 Tahun 2012 tentang Pengamanan Bahan yang Mengandung Zat Adiktif Berupa Produk Tembakau Bagi Kesehatan, Daniel menolak dan menginginkan ada kajian komprehensif yang mengutamakan kepentingan petani sebagai dasar pembuatan kebijakan pemerintah. Namun di sisi lain, Daniel juga mengatakan, “Pemerintah harus berhati-hati untuk mengambil kebijakan yang sifatnya strategis, apalagi kalau urusannya terkait dengan nasib petani, buruh dan pihak-pihak yang berhubungan dengan industri tembakau"',
          ],
        },
        {
          id: "9",
          nama: "Ir. KRT H. DARORI WONODIPURO, M.M., IPU.",
          position: { x: 0, y: 0 },
          jabatan: "Gerindra, Jateng VII",
          image: "legislatif_1_8.jpg",
          details: [
            "2018. Darori merupakan anggota panitia khusus RUU Pertembakauan dan pernah melakukan pertemuan dengan Direksi PT. Gudang Garam Indonesia dan Direksi PT. Hanjaya Mandala Sampoerna Tbk.",
            "2019. Mendukung RUU Pertembakauan harus masuk ke daftar prolegnas tahunan/5 tahunan, dan mencegah terjadinya pembatalan, karenai menilai RUU Pertembakauan nantinya akan mengatur sektor pengobatan, subsidi bagi petani tembakau dalam mengembangkan produknya, melindungi monopoli pabrik rokok lokal oleh perusahaan besar.",
          ],
        },
        {
          id: "10",
          nama: "Sunarna",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Jateng VIII",
          image: "legislatif_1_9.jpg",
          details: [
            "2013. Saat menjabat bupati Klaten, menemui petani yang melakukan aksi tolak PP Nomor 109 Tahun 2012 Pengamanan Bahan yang Mengandung Zat Adiktif Berupa Produk Tembakau Bagi Kesehatan dan menyatakan ikut mendukung penolakan PP tersebut dengan menandatangani surat dukungan penolakan PP yang akan dikirim ke pemerintah pusat. Sunarna beranggapan bahwa pemberlakuan PP tersebut sama saja dengan menghentikan sumber pendapatan petani tembakau dan perlu ada judicial review untuk PP tersebut.",
          ],
        },
        {
          id: "11",
          nama: "BAMBANG PURWANTO, S.ST., M.H.",
          position: { x: 0, y: 0 },
          jabatan: "Demokrat, Kalteng",
          image: "legislatif_1_10.jpg",
          details: [
            "2021. Menyatakan revisi PP 109 tahun 2012 tidak urgent dan menilai bahwa revisi PP 109 tidak berpihak pada petani dan akan berdampak pada penghasilan masyarakat sehingga menjadi masalah baru bagi pemerintah.",
            "2019. tercatat LHKPN sebesar Rp 951.624.000, namun sumbangan dana kampanye ke partai tahun yang sama sebesar Rp 1.753.700.000, lebih besar pasak daripada tiang. Darimana sumber sumbangan dana kampanye Bambang?",
          ],
        },
      ],
    },
    {
      id: "12",
      nama: "Komisi VI",
      position: { x: 100, y: 200 },
      description: "(Industri, Investasi, Persaingan Usaha)",
      anggota: [
        {
          id: "13",
          nama: "Nusron Wahid",
          position: { x: 0, y: 0 },
          jabatan: "Golkar, Dapil Jateng II",
          image: "legislatif_2_1.jpg",
          details: [],
        },
        {
          id: "14",
          nama: "Adisatrya Suryo Sulisto",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Jateng VIII",
          image: "legislatif_2_2.jpg",
          details: [],
        },
        {
          id: "15",
          nama: "M. SARMUJI, SE., M.Si.",
          position: { x: 0, y: 0 },
          jabatan: "Fraksi Golkar. Dapil Jawa Timur VI",
          image: "legislatif_2_3.jpg",
          details: [],
        },
        {
          id: "16",
          nama: "Dr. SUPRATMAN ANDI AGTAS, S.H., M.H.",
          position: { x: 0, y: 0 },
          jabatan: "Gerindra. Dapil Sulawesi Tengah\nKetua BALEG 2016-Sekarang",
          image: "legislatif_2_4.jpg",
          details: [],
        },
        {
          id: "17",
          nama: "LULUK NUR HAMIDAH, M.Si., M.PA.",
          position: { x: 0, y: 0 },
          jabatan:
            "PKB. Dapil Jawa Tengah IV\nAnggota Baleg, Pansus dan Komisi VI",
          image: "legislatif_2_5.jpg",
          details: [],
        },
        {
          id: "18",
          nama: "Johanes ARIA BIMA Trihastoto",
          position: { x: 0, y: 0 },
          jabatan: "Fraksi PDIP. Dapil Jawa Tengah V",
          image: "legislatif_2_6.jpg",
          details: [],
        },
        {
          id: "19",
          nama: "I NYOMAN PARTA, S.H.",
          position: { x: 0, y: 0 },
          jabatan: "PDIP. Dapil Bali",
          image: "legislatif_2_7.jpg",
          details: [],
        },
        {
          id: "20",
          nama: "Rieke Diah Pitaloka M.Hum",
          position: { x: 0, y: 0 },
          jabatan:
            "PDIP. Dapil Jawa Barat VII\nKetua Umum Konfederasi Rakyat Pekerja Indonesia (KPRI)",
          image: "legislatif_2_8.jpg",
          details: [],
        },
        {
          id: "21",
          nama: "Faisol Riza",
          position: { x: 0, y: 0 },
          jabatan: "PKB. Dapil Jawa Timur II\nKetua Komisi VI",
          image: "legislatif_2_9.jpg",
        },
      ],
    },
    {
      id: "22",
      nama: "Komisi VII",
      position: { x: 300, y: 400 },
      description: "(Energi, Riset dan Teknologi, dan Lingkungan Hidup)",
      anggota: [
        {
          id: "23",
          nama: "Marwan Jafar",
          position: { x: 0, y: 0 },
          jabatan: "PKB, Jawa Tengah III",
          image: "legislatif_3_1.jpg",
          details: [],
        },
        {
          id: "24",
          nama: "Sartono Hutomo",
          position: { x: 0, y: 0 },
          jabatan: "Demokrat, Dapil Jatim VII",
          image: "legislatif_3_2.jpg",
          details: [],
        },
        {
          id: "25",
          nama: "Bambang Haryadi",
          position: { x: 0, y: 0 },
          jabatan: "Gerindra, Dapil Jatim IV",
          image: "legislatif_3_3.jpg",
          details: [],
        },
        {
          id: "26",
          nama: "Abdul Kadir Karding",
          position: { x: 0, y: 0 },
          jabatan: "PKB, Dapil Jateng V",
          image: "legislatif_3_4.jpg",
          details: [
            "2014. Meminta pemerintah terutama Soesilo Bambang Yudhoyono yang saat itu menjabat sebagai Presiden RI untuk tidak gegabah dan memberikan persetujuan ratifikasi FCTC yang dinilai akan mengancam petani tembakau dan buruh tani.",
            "2019. Mendukung konsumsi produk tembakau asal tidak berlebihan serta pengembangan industri tembakau di Indonesia. Tidak setuju kenaikan cukai rokok kretek dan menilai kebijakan ini merupakan kebijakan salah kaprah, tergesa-gesa, dan tidak memikirkan dampaknya",
            "2023.  Menolak dan menuduh rencana revisi PP 109/2012 tentang Pengamanan Bahan yang Mengandung Zat Adiktif berupa Produk Tembakau bagi Kesehatan dan ratifikasi FCTC dikarenakan intervensi internasional ",
            "2023, Menolak revisi PP 109/2012 karena menilai akan menekan dan merugikan masyarakat.",
            "2023. Pernah memposting di sosial media pribadi terkait imbas kenaikan cukai rokok, dengan keterangan, “Gara Cukai Rokok dinaikkan terus oleh pemerintah. Makanya kejadian deh“Rokok Naik tidak boleh dihutang“.",
            "Data LHKPN tidak ditemukan, namun melaporkan sumbangan dana kampanye ke partai pada tahun 2019 sebesar Rp.1.362.650.000. Darimana sumber dana sebesar ini ya?",
          ],
        },
        {
          id: "27",
          nama: "Ir H.M.Ridwan Hisjam",
          position: { x: 0, y: 0 },
          jabatan: "Golkar, Dapil Jatim V",
          image: "legislatif_3_5.jpg",
          details: [
            "2015. Saat menjabat Wakil Ketua Komisi X DPR RI, mendorong memasukkan rokok kretek ke dalam RUU Kebudayaan sbg warisan budaya karena sifatnya unik serta meramu produksi tembakau dengan cengkeh hanya di Indonesia",
            "2018. Mendorong PT. HM Sampoerna Tbk meningkatkan capaian propernya dengan memperbanyak Tanggung Jawab Sosial Perusahaan atau Corporate Social Responsibility (CSR). Mendorong industri rokok untuk menuju industri yang ramah lingkungan",
            "2023. Menegaskan dirinya tidak akan maju lagi sebagai anggota dewan pada pemilihan legislatif 2024 mendatang. Namun putra sulungnya, Achmad Fajar Ridwan Hisjam yang akan menggantikannya maju sebagai calon anggota DPR RI untuk Daerah Pemilihan (Dapil) Jawa Timur V Malang Raya",
          ],
        },
        {
          id: "28",
          nama: "Ribka Tjiptaning Proletariyati",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Jabar IV",
          image: "legislatif_3_6.jpg",
          details: [
            "2012. Terlibat kasus hilangnya ayat tembakau dalam RUU Kesehatan. Dalam ayat 2 pasal 113 RUU, tembakau disebut sebagai zat adiktif. Ayat tersebut tiba-tiba dihilangkan, padahal pada saat pembahasan, yaitu 11 September 2009, ada dalam naskah. Saat itu Ribka merupakan ketua komisi IX dan diberi sanksi oleh Badan Kehormatan DPR berupa larangan memimpin rapat panitia kerja dan panitia khusus. ",
            "2013. Menerima aspirasi Asosiasi Petani Tembakau Indonesia untuk dibawa dalam rapat dengan Kementerian Kesehatan RI ataupun Kementerian Tenaga Kerja RI, saat menjabat sebagai Komisi IX DPR RI.",
          ],
        },
        {
          id: "29",
          nama: "Syaikhul Islam Ali",
          position: { x: 0, y: 0 },
          jabatan: "PKB, Dapil Jatim I",
          image: "legislatif_3_7.jpg",
          details: [
            "2018. Memimpin kunjungan ke PT. HM Sampoerna Tbk di Sukorejo, Pasuruan, Jawa Timur. Menyatakan dukungan pada PT Sampoerna meningkatkan Penilaian Peringkat Kinerja Perusahaan (Proper) Hijau ke Emas agar dapat menjadi pionir bagi industri rokok ramah lingkungan. Menyatakan limbah B3 dari industri rokok tidak terlalu banyak, jadi mudah untuk menuju industri yang ramah lingkungan.",
          ],
        },
      ],
    },
    {
      id: "30",
      nama: "Komisi IX",
      position: { x: 500, y: 600 },
      description: "(Kesehatan, Ketenagakerjaan, Kependudukan)",
      anggota: [
        {
          id: "31",
          nama: "Hj. NUR NADLIFAH, S.Ag., M.M.",
          position: { x: 0, y: 0 },
          jabatan: "PKB, Jawa Tengah IX",
          image: "legislatif_4_1.jpg",
          details: [
            "2021. Menolak kenaikan tarif cukai hasil tembakau (CHT) karena akan berpengaruh terhadap kesejahteraan serta kelangsungan hidup petani dan tenaga kerja industri hasil tembakau (IHT)",
            "2022. Menyatakan tidak setuju dengan pemerintah yang menaikkan tarif cukai SKT pada 2023 dan menilai kontribusi segmen ini besar pada pemulihan ekonomi negara melalui pabrikan Sigaret Kretek Tangan (SKT) dan penyerapan tenaga kerja",
            "2022. Menilai  IHT, telah memberikan kontribusi yang besar bagi negara. Menuduh adanya intervensi dan kampanye hitam yang ingin menghancurkan IHT dalam negeri. Berpendapat bahwa tidak ada negara lain yang model sektor pertembakauannya seperti di Indonesia karena jenis rokok kretek itu budaya asli kita",
            "2023. Tidak setuju dengan penyamaan produk tembakau dengan narkotika dan psikotropika. ",
            "2023, Mendukung hasil pertemuan (P3M) yang lalu. Kami memang ingin mengarahkan aturan (produk tembakau) ini dikeluarkan dari RPP kesehatan, Sebab, dalam RPP Kesehatan memuat banyak larangan bagi produk tembakau tersebut, mengesankan produk tembakau seolah produk terlarang. Upaya ini mengindikasikan adanya upaya untuk menyetarakan produk tembakau dengan narkotika dan psikotropika.",
          ],
        },
        {
          id: "32",
          nama: "Dra. Lucy Kurniasari",
          position: { x: 0, y: 0 },
          jabatan: "Demokrat, Jawa Timur I",
          image: "legislatif_4_2.jpg",
          details: [
            "2023. Menyatakan pasal 154 hingga 158 yang menyetarakan tembakau dengan narkoba seharusnya dihapus dari RUU Kesehatan. Berpendapat bahwa Pasal itu akan bertentangan dengan pasal lain pada UU lain yang melegalkan tembakau. Mengemukakan bahwa pasal tersebut bisa membunuh usaha tembakau dan menghilangkan mata pencaharian para petani tembakau dan khawatir dengan tutupnya pabrik rokok dan bertambahnya pengangguran.",
          ],
        },
        {
          id: "33",
          nama: "M. Yahya Zaini, S.H",
          position: { x: 0, y: 0 },
          jabatan: "Golkar, Jawa Tengah VIII",
          image: "legislatif_4_3.jpg",
          details: [
            "2023.  Tidak setuju penyatuan zat narkotika dengan produk tembakau dalam satu kategori. Mengusulkan adanya aturan terpisah untuk zat narkotika dan tembakau, termasuk rokok elektrik sebagai salah satu produk turunannya. Menilai bahwa industri tembakau telah menjadi bagian integral dari sejarah dan kebudayaan Indonesia selama lebih dari seratus tahun. Beranggapan bahwa negara telah menerima banyak dari industri rokok serta menjadi salah satu penyedia lapangan pekerjaan terbesar di Indonesia.",
            "2023, menyatakan bahwa IHT itu industri yang legal, jangan terus dipersulit. Kontribusinya sangat nyata bagi negara.  Dia menyebutkan bahwa IHT menyerap lapangan kerja 5-6 juta orang. Cukai rokok sebesar Rp 232 triliun bagi keuangan negara. Dia mengungkapkan bahwa tidak ada industri lain yang kontribusinya sebesar IHT.",
          ],
        },
        {
          id: "34",
          nama: "H. Abidin Fikri, S.H. M.H",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Jawa Tengah IX",
          image: "legislatif_4_4.jpg",
          details: [
            "2021. Menerima audiensi dari Aliansi Masyarakat Tembakau Indonesia (AMTI) yang terdiri dari Asosiasi Petani Tembakau Indonesia (APTI), Asosiasi Petani Cengkeh Indonesia (APCI) dan Mitra Produksi Sigaret Indonesia (MPSI) dan menyatakan menerima aduan AMTI mengenai revisi PP 109/2012. Menyatakan dukungan untuk tidak merevisi PP 109 Tahun 2012 karena kekhawatiran akan banyak para pelaku usaha dalam industri hasil tembakau yang gulung tikar dan berdampak pada pengangguran",
            "2023. Cenderung tidak setuju dengan rencana pelarangan iklan produk tembakau atau iklan rokok di ruang publik maupun internet di dalam draft Peraturan Pemerintah (PP) yang sedang disusun Kementerian Kesehatan (Kemenkes). Menekankan agar pengaturan pengendalian tembakau Jangan sampai ini menjadi pengekang industri kreatif.",
          ],
        },
      ],
    },
    {
      id: "35",
      nama: "Komisi XI",
      position: { x: 700, y: 800 },
      description:
        "(Keuangan, Perencanaan Pembangunan Nasional, serta Perbankan)",
      anggota: [
        {
          id: "36",
          nama: "Ir. Andreas Susetyo",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Jatim V",
          image: "legislatif_5_1.jpg",
          details: [
            "Pernah menjabat sebagai Komite Pemantau Risiko PT Bank Central Asia Tbk. (Salah satu perusahaan yang satu group dengan Djarum) 2008-2014.",
            "2022. Pernyataan: “Kenaikan tarif CHT itu telah membuat para pekerja di dalamnya merasa terancam, karena memang daya beli masyarakat tengah sulit dan belum adanya roadmap yang memberi peluang kerja baru bagi mereka … “ Pernyataan disampaikan saat rapat kerja DPR dengan Menteri Keuangan RI.",
          ],
        },
        {
          id: "37",
          nama: "Prof. Dr. Hendrawan Supratikno",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Jateng X",
          image: "legislatif_5_2.jpg",
          details: [
            "2018. Wakil Ketua Panitia Khusus (Pansus) RUU Pertembakauan",
            "2019. Mendorong pembahasan RUU Pertembakauan karena menilai sektor pertembakauan telah memberikan manfaat dari segi ekonomi yang cukup besar dalam penerimaan negara",
            '2022. Meminta semua pihak memperhitungkan dampak kenaikan cukai rokok terhadap kesempatan kerja dan daya serap tembakau petani. Beliau menilai hubungan antara besaran cukai rokok dan penerimaan negara tidak selamanya berbanding lurus.\nPernyataan: "Pada suatu titik, kenaikan tarif cukai justru akan menurunkan penerimaan. Fenomena ini sering disebut kurva laffer.',
          ],
        },
        {
          id: "38",
          nama: "Bertu Merlas",
          position: { x: 0, y: 0 },
          jabatan: "PKB, Dapil Sumsel II",
          image: "legislatif_5_3.jpg",
          details: [
            '2021. Tidak sepakat dengan kenaikan cukai rokok atau cukai hasil tembakau pada 1 Februari 2021 karena dinilai mengancam kesejahteraan petani tembakau. Pernyataan: "Cukai tembakau setiap tahun mengalami kenaikan, sementara para petani tembakau terus mengalami tekanan akan kenaikan tersebut"',
            '2021. “Mengenai perhatian terhadap petani tembakau ini, kita di sini memperhatikan (kalau) aspek kesehatan ini sudah kita bawa di bagi persentasenya hasil cukai untuk kesehatan sekian persen, namun untuk petani sendiri yang notabene hasil cukai ini juga berdampak pada penerimaan negara, tak ada satu tetespun yang dialokasikan ke sana,"',
            "2022. Menilai produk rokok dari Golongan SKT berasal dari 100% tembakau yang diproduksi petani tembakau dalam negeri. Adanya kenaikan dianggap akan banyak berimplikasi kepada petani serta permintaan yang turun akibat tarifnya naik hingga 5%.",
            "2022. Mengusulkan penggolongan tarif Cukai Rokok Elektrik (REL) untuk produk rokok elektrik yang diproduksi oleh industri kecil dan industri kreatif tanah air agar tidak disamaratakan. Hal ini disampaikan menanggapi wacana kenaikan tarif Cukai Hasil Tembakau, termasuk Rokok Elektrik (REL) dan Hasil Pengolahan Tembakau Lainnya (HPTL).",
          ],
        },
        {
          id: "39",
          nama: "H. M. Amir Uskara",
          position: { x: 0, y: 0 },
          jabatan: "PPP, Dapil Sulsel I",
          image: "legislatif_5_4.jpg",
          details: [
            '2022. Pernyataan: “Kenaikan cukai rokok memang dibutuhkan untuk memperkuat penerimaan dalam APBN, tapi kenaikan tersebut perlu dibatasi.\n“Karena itu, untuk tahun 2023 disarankan batas maksimum kenaikan cukai rokok adalah di kisaran tujuh persen"',
            "Menilai bahwa kenaikan cukai terlampau tinggi akan berdampak signifikan. Kesempatan kerja di sektor industri hasil tembakau akan terkena imbas, mulai dari petani, sektor industri pengolahan tembakau, hingga para pedagang kaki lima.",
          ],
        },
        {
          id: "40",
          nama: "Willy Aditya",
          position: { x: 0, y: 0 },
          jabatan:
            "Wakil Ketua Fraksi Partai NasDem DPR RI.\nDapil Jawa Timur XI\nWakil Ketua Badan Legislasi DPR RI\nKetua DPP Partai Nasdem",
          image: "legislatif_5_5.jpg",
          details: [
            '2021. Menunjukkan sikap kontra kenaikan cukai hasil tembakau. Pernyataan: “Selain menurunkan produktivitas IHT, kenaikan CHT akan menyuburkan pasar rokok ilegal,..."',
            "2021. Mendorong adanya insentif bagi industri Hasil Pengolahan Tembakau dan Lainnya (HPTL) karena berkontribusi bagi peningkatan penerimaan cukai negara. ",
            '2021. Pernyataan: "Perlu ada langkah pemerintah untuk mengatasi ini (angka prevalensi usia merokok dalam rentang 10-18 tahun, yang sering tidak terealisasi), sehingga alasan untuk menaikkan cukai rokok menjadi sejalan dengan kebijakan yang diterapkan. Kedepannya, pemerintah juga perlu membuat blue print arah kebijakan cukai tembakau khusus dalam optimalisasi juga sangat dibutuhkan" Menerima audiensi dari AMTI, pada tanggal 20 Mei 2022.',
          ],
        },
        //TODO: IMAGE NOT FOUND
        {
          id: "41",
          nama: "Racmat Gobel",
          position: { x: 0, y: 0 },
          jabatan: "Nasdem, Dapil Gorontalo 1",
          image: "legislatif_5_6.jpg",
          details: [],
        },
        {
          id: "42",
          nama: "Ir. Dolfie Othniel Frederic Palit",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Jateng IV",
          image: "legislatif_5_7.jpg",
          details: [
            '2022. Bersama Komisi XI DPR RI, ikut mengkritisi kebijakan pemerintah yang menetapkan tarif cukai hasil tembakau (CHT) tahun anggaran 2023 dan 2024 tanpa terlebih dahulu melalui persetujuan para anggota dewan.\nPernyataan: “Keputusan itu bertentangan dengan prinsip hubungan kesetaraan hak penganggaran atau budgeting. Karena itu, seharusnya penetapan CHT itu harus dikonsultasikan sebelum adanya kesepakatan UU APBN 2023 yang telah ditetapkan pada November 2022."',
            '2022. Meminta pemerintah untuk segera menyusun peta jalan (roadmap) transformasi industri hasil tembakau (IHT).\nPernyataan: “Ada kontradiksi antara penerapan kebijakan kenaikan tarif cukai tembakau dengan target penurunan prevalensi perokok di Indonesia yang selalu digadang-gadang oleh pemerintah."',
          ],
        },
        {
          id: "43",
          nama: "Dr. H. Mustofa, SE., MM",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Jateng II",
          image: "legislatif_5_8.jpg",
          details: [
            "2020. Mengunjungi beberapa pabrik rokok untuk mendengarkan permasalahan yang dihadapi para pengusaha rokok serta pekerja di Kudus.",
            '2020. Menghadiri peremsian KIHT (Kawasan Industri Hasil Tembakau) di Kudus. “Maksud dan tujuan pembentukan KIHT ini adalah memberikan kemudahan, membangun kekuatan perekonomian bagi masyarakat kecil yang berusaha di bidang rokok." ',
          ],
        },
        {
          id: "44",
          nama: "Said Abdullah",
          position: { x: 0, y: 0 },
          jabatan: "PDIP, Dapil Jatim XI",
          image: "legislatif_5_9.jpg",
          details: [
            '2020. Mendorong segera terbentuknya kawasan industri hasil tembakau (KIHT) di Pulau Madura, sebagai bentuk proteksi bagi industri kecil menengah.\nPernyataan: “Sudah waktunya di Madura ada KIHT. Ini akan membantu pabrikan rokok kecil agar bisa bertahan sekaligus terus mengembangkan usahanya,"',
            '2023, “Tembakau campalok ini berhikayat mistis, termasuk harganya luar biasa mahal, dan ternyata tembakau ini bisa digunakan untuk vaksin invfluenza sekaligus obat obat herbal. Bagi orang madura adalah dirinya, bagi orang madura tembakau adalah kecintaan, bagi orang madura tembakau adalah gantungan emas yang tidak mungkin ia tinggalkan,"',
          ],
        },
      ],
    },
  ],
};

const eksekutif = {
  id: "91",
  nama: "Eksekutif",
  position: { x: 3062, y: 1816 },
  details: [
    {
      id: "47",
      nama: "Atong Soekirman",
      position: { x: 2632, y: 1959 },
      jabatan: "Asisten Deputi Pengembangan Industri",
      image: "eksekutif_1_1.jpg",
      details: [],
    },
    {
      id: "48",
      nama: "Airlangga Hartanto",
      position: { x: 2539, y: 1789 },
      jabatan: "Menko Perekonomian, Golkar",
      image: "eksekutif_1_2.jpg",
      details: [],
    },
    {
      id: "49",
      nama: "Moch Edy Yusuf",
      position: { x: 2632, y: 1623 },
      jabatan: "Asisten Deputi Pengembangan Agribisnis Perkebunan",
      image: "eksekutif_1_3.jpg",
      details: [],
    },
    {
      id: "50",
      nama: "Susiwijono Moegiarso",
      position: { x: 2790, y: 1471 },
      jabatan: "Sekretaris",
      image: "eksekutif_1_4.jpg",
      details: [],
    },
    {
      id: "51",
      nama: "Eddy Abdurachman",
      position: { x: 2981, y: 1451 },
      jabatan: "Direktur Utama BPDPKS",
      image: "eksekutif_child_2_1.jpg",
      details: [],
    },
    {
      id: "52",
      nama: "Hendratmojo Bagus Hudoro",
      position: { x: 3196, y: 2188 },
      jabatan: "Direktur Tanaman Semusim dan Rempah",
      image: "eksekutif_child_2_2.jpg",
      details: [],
    },
    {
      id: "55",
      nama: "Edy Sutopo",
      position: { x: 3668, y: 1805 },
      jabatan: "Direktur Industri Minuman, Hasil Tembakau dan Bahan Penyegar",
      image: "eksekutif_3_1.jpg",
      details: [],
    },
    {
      id: "56",
      nama: "Putu Juli Ardika",
      position: { x: 3550, y: 1985 },
      jabatan: "Direktur Jenderal Industri Agro",
      image: "eksekutif_3_2.jpg",
      details: [],
    },
    {
      id: "57",
      nama: "Agus Gumiwang Kartasasmita",
      position: { x: 3411, y: 2139 },
      jabatan: "Menteri Perindustrian",
      image: "eksekutif_3_3.jpg",
      details: [],
    },
    {
      id: "59",
      nama: "Yaqub Ginting",
      position: { x: 2981, y: 2188 },
      jabatan: "Ketua Tim Kerja Tanaman Semusim dan yang Lainnya",
      image: "eksekutif_5_1.jpg",
      details: [],
    },
    {
      id: "60",
      nama: "Kasdi Subagyono",
      position: { x: 2790, y: 2139 },
      jabatan: "Sekertaris Jenderal Perkebunan Kementan",
      image: "eksekutif_5_2.jpg",
      details: [],
    },
    {
      id: "61",
      nama: "Budi Arie Setiadi",
      position: { x: 3196, y: 1450 },
      jabatan: "Menteri Komunikasi dan Informatika",
      image: "eksekutif_5_3.jpg",
      details: [],
    },
    {
      id: "62",
      nama: "Nyoman Adhiarna",
      position: { x: 3413, y: 1471 },
      jabatan: "Sekretaris Direktorat Jenderal Aplikasi Informatika",
      image: "eksekutif_5_4.jpg",
      details: [],
    },
    {
      id: "63",
      nama: "Indah Anggoro Putri",
      position: { x: 3579, y: 1623 },
      jabatan:
        "Direktur Jenderal Pembinaan Hubungan Industrial dan Jaminan Sosial Tenaga Kerja",
      image: "eksekutif_5_5.jpg",
      details: [],
    },
    {
      id: "64",
      nama: "Eni Maulani Saragih",
      position: { x: 1600, y: 0 },
      jabatan: "Mantan anggota DPR Komisi VII",
      image: "eksekutif_5_6.jpg",
      details: [],
    },
    {
      id: "65",
      nama: "Muhammad Al Khadziq",
      position: { x: 1600, y: 0 },
      jabatan: "Bupati Temanggung",
      image: "eksekutif_5_7.jpg",
      details: [],
    },
  ],
};

const tobacco_industri = {
  id: "92",
  nama: "Tobacco Industry (& afiliasi)",
  position: { x: 0, y: -1600 },
  details: [
    {
      id: "66",
      nama: "PT HM Sampoerna Tbk",
      image: "sampoerna.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "67",
      nama: "PT Gudang Garam",
      image: "gudang-garam.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "68",
      nama: "PT Bentoel Internasional Investama Tbk",
      image: "bentoel.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "69",
      nama: "PT Djarum",
      image: "djarum.jpg",
      position: { x: 0, y: 0 },
    },
  ],
};

const front_group_ti = {
  id: "93",
  nama: "Front Groups TI",
  position: { x: 0, y: 1600 },
  details: [
    {
      id: "70",
      nama: "Aliansi Masyarakat Tembakau Indonesia",
      image: "AMTI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "71",
      nama: "Komite Ekonomi Rakyat Indonesia Semesta (KERIS)",
      image: "KERIS.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "72",
      nama: "Forum Masyarakat Industri Rokok Seluruh Indonesia (FORMASI)",
      image: "FORMASI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "73",
      nama: "Asosiasi Petani Tembakau Indonesia (APTI)",
      image: "APTI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "74",
      nama: "Gabungan Perserikatan Pabrik Rokok Indonesia (GAPPRI)",
      image: "GAPPRI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "75",
      nama: "Gabungan Produsen Rokok Putih Indonesia (GAPRINDO)",
      image: "GAPRINDO.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "76",
      nama: "Lembaga Kajian dan Pengembangan Sumber Daya Manusia (LAKPESDAM)",
      image: "LAKPESDAM.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "77",
      nama: "Institute For Development of Economics and Finance",
      image: "IDEF.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "78",
      nama: "Koalisi Indonesia Bebas TAR (KABAR)",
      image: "KABAR.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "79",
      nama: "Federasi Serikat Pekerja Rokok Tembakau Makanan dan Minuman Serikat Pekerja Seluruh Indonesia (FSP RTMM SPSI)",
      image: "FSP_RTMM_SPSI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "89",
      nama: "Mitra Produksi Sigaret Indonesia (MPSI)",
      image: "MPSI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "81",
      nama: "Asosiasi Petani Cengkeh Indonesia (APCI)",
      image: "APCI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "82",
      nama: "Lembaga Konsumen Rokok Indonesia (LKRI)",
      image: "LKRI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "83",
      nama: "Asosiasi Koperasi Ritel Indonesia (AKRINDO)",
      image: "AKRINDO.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "84",
      nama: "Komite Nasional Pelestarian Kretek(KNPT)",
      image: "KNPT.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "85",
      nama: "Gabungan Perusahaan Rokok Surabaya(Gaperosu)",
      image: "Gaperosu.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "86",
      nama: "Himpunan Kerukunan Tani Indonesia (HKTI)",
      image: "HKTI.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "87",
      nama: "Komunitas Perokok Bijak (Kojak)",
      image: "Kojak.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "88",
      nama: "Asosiasi Pengusaha Indonesia",
      image: "API.jpg",
      position: { x: 0, y: 0 },
    },
    {
      id: "89",
      nama: "Gabungan Perusahaan Rokok Malang(Gaperoma)",
      image: "Gaperoma.jpg",
      position: { x: 0, y: 0 },
    },
  ],
};

const listNodes = {
  legislatif: legislatif,
  eksekutif: eksekutif,
  tobacco_industri: tobacco_industri,
  front_group_ti: front_group_ti,
};

export default listNodes;
