const listEdges = [
  {
    id: "e91-47",
    source: "91",
    target: "47",
    sourceHandle: "d",
    targetHandle: "f",
    type: "straight",
    label: null,
  },
  {
    id: "e91-48",
    source: "91",
    target: "48",
    sourceHandle: "d",
    targetHandle: "f",
    type: "straight",
    label: null,
  },
  {
    id: "e91-49",
    source: "91",
    target: "49",
    sourceHandle: "d",
    targetHandle: "f",
    type: "straight",
    label: null,
  },
  {
    id: "e91-50",
    source: "91",
    target: "50",
    sourceHandle: "a",
    targetHandle: "g",
    type: "straight",
    label: null,
  },
  {
    id: "e91-51",
    source: "91",
    target: "51",
    sourceHandle: "a",
    targetHandle: "g",
    type: "straight",
    label: null,
  },
  {
    id: "e91-61",
    source: "91",
    target: "61",
    sourceHandle: "a",
    targetHandle: "g",
    type: "straight",
    label: null,
  },
  {
    id: "e91-62",
    source: "91",
    target: "62",
    sourceHandle: "a",
    targetHandle: "g",
    type: "straight",
    label: null,
  },
  {
    id: "e91-63",
    source: "91",
    target: "63",
    sourceHandle: "b",
    targetHandle: "h",
    type: "straight",
    label: null,
  },
  {
    id: "e91-55",
    source: "91",
    target: "55",
    sourceHandle: "b",
    targetHandle: "h",
    type: "straight",
    label: null,
  },
  {
    id: "e91-56",
    source: "91",
    target: "56",
    sourceHandle: "b",
    targetHandle: "h",
    type: "straight",
    label: null,
  },
  {
    id: "e91-59",
    source: "91",
    target: "59",
    sourceHandle: "c",
    targetHandle: "e",
    type: "straight",
    label: null,
  },
  {
    id: "e91-60",
    source: "91",
    target: "60",
    sourceHandle: "c",
    targetHandle: "e",
    type: "straight",
    label: null,
  },
  {
    id: "e91-52",
    source: "91",
    target: "52",
    sourceHandle: "c",
    targetHandle: "e",
    type: "straight",
    label: null,
  },
  {
    id: "e91-57",
    source: "91",
    target: "57",
    sourceHandle: "c",
    targetHandle: "e",
    type: "straight",
    label: null,
  },
];

export default listEdges;
