import { lineBlack, lineDarkBrown, lineGreen } from "../../../public/colors";

const listEdges = [
  // Ekse top
  {
    id: "e91-50",
    source: "91",
    target: "50",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e91-51",
    source: "91",
    target: "51",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e91-61",
    source: "91",
    target: "61",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e91-62",
    source: "91",
    target: "62",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  // ekse right
  {
    id: "e91-63",
    source: "91",
    target: "63",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e91-57",
    source: "91",
    target: "57",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e91-55",
    source: "91",
    target: "55",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },

  // ekse bot
  {
    id: "e91-56",
    source: "91",
    target: "56",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e91-49",
    source: "91",
    target: "49",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e91-48",
    source: "91",
    target: "48",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e91-47",
    source: "91",
    target: "47",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // ekse left
  {
    id: "e91-59",
    source: "91",
    target: "59",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e91-52",
    source: "91",
    target: "52",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e91-60",
    source: "91",
    target: "60",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },

  // legislatif komisi IV
  {
    id: "e90-12",
    source: "90",
    target: "1",
    type: "step",
    sourceHandle: "a",
    targetHandle: "h",
    color: lineBlack,
  },

  // anggota IV top
  {
    id: "e1-3",
    source: "1",
    target: "3",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e1-22",
    source: "1",
    target: "2",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e1-5",
    source: "1",
    target: "5",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },

  // anggota IV right
  {
    id: "e1-6",
    source: "1",
    target: "6",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e1-7",
    source: "1",
    target: "7",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e1-8",
    source: "1",
    target: "8",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },

  // anggota IV bot
  {
    id: "e1-9",
    source: "1",
    target: "9",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e1-10",
    source: "1",
    target: "10",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e1-11",
    source: "1",
    target: "11",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // komisi VI
  {
    id: "e90-12",
    source: "90",
    target: "12",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },

  // anggota VI top
  {
    id: "e12-14",
    source: "12",
    target: "14",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e12-20",
    source: "12",
    target: "20",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e12-19",
    source: "12",
    target: "19",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },

  // anggota VI left
  {
    id: "e12-21",
    source: "12",
    target: "21",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e12-13",
    source: "12",
    target: "13",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e12-15",
    source: "12",
    target: "15",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },

  // anggota VI bot
  {
    id: "e12-16",
    source: "12",
    target: "16",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e12-17",
    source: "12",
    target: "17",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e12-18",
    source: "12",
    target: "18",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // komisi VII
  {
    id: "e90-22",
    source: "90",
    target: "22",
    type: "step",
    sourceHandle: "c",
    targetHandle: "h",
    color: lineBlack,
  },

  // anggota VII top
  {
    id: "e22-24",
    source: "22",
    target: "24",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e22-28",
    source: "22",
    target: "28",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },

  // anggota VII right
  {
    id: "e22-26",
    source: "22",
    target: "26",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e22-25",
    source: "22",
    target: "25",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e22-27",
    source: "22",
    target: "27",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },

  // anggota VII bot
  {
    id: "e22-29",
    source: "22",
    target: "29",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e22-93",
    source: "22",
    target: "93",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // komisi IX
  {
    id: "e90-30",
    source: "90",
    target: "30",
    type: "step",
    sourceHandle: "c",
    targetHandle: "f",
    color: lineBlack,
  },

  // anggota IX top
  {
    id: "e30-32",
    source: "30",
    target: "32",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },

  // anggota IX left
  {
    id: "e30-31",
    source: "30",
    target: "31",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e30-33",
    source: "30",
    target: "33",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },

  // anggota IX bot
  {
    id: "e30-34",
    source: "30",
    target: "34",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e30-95",
    source: "30",
    target: "95",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // Komisi XI
  {
    id: "e30-95",
    source: "30",
    target: "95",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // anggota XI top
  {
    id: "e35-38",
    source: "35",
    target: "38",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e35-42",
    source: "35",
    target: "42",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },

  // anggota XI left
  {
    id: "e35-40",
    source: "35",
    target: "40",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e35-43",
    source: "35",
    target: "43",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e35-44",
    source: "35",
    target: "44",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },

  // anggota XI left
  {
    id: "e35-37",
    source: "35",
    target: "37",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e35-39",
    source: "35",
    target: "39",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e35-36",
    source: "35",
    target: "36",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // tobacco industry
  {
    id: "e92-66",
    source: "92",
    target: "66",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e92-67",
    source: "92",
    target: "67",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e92-68",
    source: "92",
    target: "68",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e92-69",
    source: "92",
    target: "69",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },

  // Front Group TI
  {
    id: "e96-70",
    source: "96",
    target: "70",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e96-73",
    source: "96",
    target: "73",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e96-75",
    source: "96",
    target: "75",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e96-83",
    source: "96",
    target: "83",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },
  {
    id: "e96-76",
    source: "96",
    target: "76",
    type: "step",
    sourceHandle: "a",
    targetHandle: "g",
    color: lineBlack,
  },

  // FG left
  {
    id: "e96-94",
    source: "96",
    target: "94",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e96-72",
    source: "96",
    target: "72",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },
  {
    id: "e96-78",
    source: "96",
    target: "78",
    type: "step",
    sourceHandle: "d",
    targetHandle: "f",
    color: lineBlack,
  },

  // FG bot
  {
    id: "e96-79",
    source: "96",
    target: "79",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },
  {
    id: "e96-74",
    source: "96",
    target: "74",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  {
    id: "e96-71",
    source: "96",
    target: "71",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  {
    id: "e96-89",
    source: "96",
    target: "89",
    type: "step",
    sourceHandle: "c",
    targetHandle: "e",
    color: lineBlack,
  },

  // FG right
  {
    id: "e96-97",
    source: "96",
    target: "97",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e96-86",
    source: "96",
    target: "86",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },
  {
    id: "e96-81",
    source: "96",
    target: "81",
    type: "step",
    sourceHandle: "b",
    targetHandle: "h",
    color: lineBlack,
  },

  // ekse external
  // {
  //   id: "e51-68",
  //   source: "51",
  //   target: "68",
  //   type: "smart",
  //   sourceHandle: "a",
  //   targetHandle: "h",
  //   color: lineGreen,
  // },

  // hendratmojo
  // {
  //   id: "e52-70",
  //   source: "52",
  //   target: "70",
  //   type: "smart",
  //   sourceHandle: "d",
  //   targetHandle: "e",
  //   color: lineDarkBrown,
  // },
  // {
  //   id: "e52-97",
  //   source: "52",
  //   target: "97",
  //   type: "smart",
  //   sourceHandle: "d",
  //   targetHandle: "b",
  //   color: lineDarkBrown,
  // },
  // {
  //   id: "e52-81",
  //   source: "52",
  //   target: "81",
  //   type: "smart",
  //   sourceHandle: "d",
  //   targetHandle: "b",
  //   color: lineDarkBrown,
  // },
];

export default listEdges;
