export const categories: { id: string, position: string }[] = [
    { id: '1', position: 'DPR RI' },
    { id: '2', position: 'Calon Gubernur' }
];

export const indonesiaProvinces: { id: string, title: string }[] = [
    { id: "ID-AC", title: "Nanggroe Aceh Darussalam" },
    { id: "ID-BA", title: "Bali" },
    { id: "ID-BB", title: "Bangka Belitung" },
    { id: "ID-BE", title: "Bengkulu" },
    { id: "ID-BT", title: "Banten" },
    { id: "ID-GO", title: "Gorontalo" },
    { id: "ID-JA", title: "Jambi" },
    { id: "ID-JB", title: "Jawa Barat" },
    { id: "ID-JI", title: "Jawa Timur" },
    { id: "ID-JK", title: "DKI Jakarta" },
    { id: "ID-JT", title: "Jawa Tengah" },
    { id: "ID-KB", title: "Kalimantan Barat" },
    { id: "ID-KI", title: "Kalimantan Timur" },
    { id: "ID-KR", title: "Kepulauan Riau" },
    { id: "ID-KS", title: "Kalimantan Selatan" },
    { id: "ID-KT", title: "Kalimantan Tengah" },
    { id: "ID-KU", title: "Kalimantan Utara" },
    { id: "ID-LA", title: "Lampung" },
    { id: "ID-MA", title: "Maluku" },
    { id: "ID-MU", title: "Maluku Utara" },
    { id: "ID-NB", title: "Nusa Tenggara Barat" },
    { id: "ID-NT", title: "Nusa Tenggara Timur" },
    { id: "ID-PA", title: "Papua" },
    { id: "ID-PB", title: "Papua Barat" },
    { id: "ID-PBD", title: "Papua Barat Daya" },
    { id: "ID-PP", title: "Papua Pegunungan" },
    { id: "ID-PS", title: "Papua Selatan" },
    { id: "ID-PT", title: "Papua Tengah" },
    { id: "ID-RI", title: "Riau" },
    { id: "ID-SA", title: "Sulawesi Utara" },
    { id: "ID-SB", title: "Sumatera Barat" },
    { id: "ID-SG", title: "Sulawesi Tenggara" },
    { id: "ID-SN", title: "Sulawesi Selatan" },
    { id: "ID-SR", title: "Sulawesi Barat" },
    { id: "ID-SS", title: "Sumatera Selatan" },
    { id: "ID-ST", title: "Sulawesi Tengah" },
    { id: "ID-SU", title: "Sumatera Utara" },
    { id: "ID-YO", title: "Daerah Istimewa Yogyakarta" }
];
